name: Deploy API Gateway

on:
  push:
    branches:
      - master
    paths:
      - cdk/infraestructure/api-gateway/**
      - .github/workflows/deploy-api-gateway.yml

concurrency:
  group: "${{ github.ref_name }}-deploy-api-gateway"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - destination-region: ${{ vars.AWS_REGION_US_EAST_1 }}
          - destination-region: ${{ vars.AWS_REGION_US_WEST_2 }}
    name: Deploy to ${{ matrix.destination-region }}
    permissions:
      id-token: write
      contents: read
    environment: dev
    env:
      ENV_NAME: dev
      AWS_DEPLOY_REGION: ${{ matrix.destination-region }}
      AWS_DEPLOY_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
      CORS_ALLOW_ORIGINS: ${{ vars.CORS_ALLOW_ORIGINS }}
      CORS_EXPOSE_HEADERS: ${{ vars.CORS_EXPOSE_HEADERS }}
    steps:
      - name: Setup actions
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_DEPLOY_ACCOUNT }}:role/github-cicd
          aws-region: ${{ env.AWS_DEPLOY_REGION }}

      - name: Deploy Stack
        run: |
          sudo npm install -g aws-cdk
          cd cdk/infraestructure/api-gateway && npm install
          cdk deploy api-gateway-stack --require-approval never
        shell: bash

      - name: Add summary
        run: |
          echo "## Deployed in ${{env.AWS_DEPLOY_REGION}} ${{env.ENV_NAME}} environment :smile: :rocket:" >> $GITHUB_STEP_SUMMARY
        shell: bash